---
title: "EDA"
output: pdf_document
---

```{r include=FALSE}
library(tidyverse)
library(tinytex)
library(lme4)
```

```{r include=FALSE}
Judge  <- read_csv("Data/judge_batting_2024.csv")
Ohtani <- read_csv("Data/ohtani_batting_2024.csv")
Betts  <- read_csv("Data/betts_batting_2024.csv")
```

```{r include=FALSE}
#Re-orders the data into time increasing instead of time decreasing
Judge1 <- Judge %>%
  group_by(game_date, inning, pitch_number) %>%
  arrange(desc(game_date), .by_group = TRUE) %>%
  ungroup() %>%
  mutate(week = as.numeric(strftime(game_date, format = "%V")),
         week = week-min(week)+1)
Ohtani1 <- Ohtani %>%
  group_by(game_date, inning, pitch_number) %>%
  arrange(desc(game_date), .by_group = TRUE) %>%
  ungroup() %>%
  mutate(week = as.numeric(strftime(game_date, format = "%V")),
         week = week-min(week)+1)
Betts1 <- Betts %>%
  group_by(game_date, inning, pitch_number) %>%
  arrange(desc(game_date), .by_group = TRUE) %>%
  ungroup() %>%
  mutate(week = as.numeric(strftime(game_date, format = "%V")),
         week = week-min(week)+1)
```


```{r warning=FALSE, include=FALSE}
Judge2 <- Judge1 %>%
  filter(description == "hit_into_play") %>%
  mutate(outcome = case_when(
    events == c("single", "double", "triple", "home_run", "sac_fly") ~ "HitGood",
    events != c("single", "double", "triple", "home_run", "sac_fly") ~ "HitBad"
    )
  )
Ohtani2 <- Ohtani1 %>%
  filter(description == "hit_into_play") %>%
  mutate(outcome = case_when(
    events == c("single", "double", "triple", "home_run", "sac_fly") ~ "HitGood",
    events != c("single", "double", "triple", "home_run", "sac_fly") ~ "HitBad"
    )
  )
Betts2 <- Betts1 %>%
  filter(description == "hit_into_play") %>%
  mutate(outcome = case_when(
    events == c("single", "double", "triple", "home_run", "sac_fly") ~ "HitGood",
    events != c("single", "double", "triple", "home_run", "sac_fly") ~ "HitBad"
    )
  )
```

```{r include=FALSE}
Judge3 <- cbind(
  Judge1 %>%
    group_by(week)%>%
    summarise(pitches = n()) %>%
    select(week, pitches),
  Judge2 %>%
    group_by(week) %>%
    summarise(hits = n()) %>%
    select(hits),
  Judge2 %>%
    group_by(week) %>%
    filter(outcome=="HitBad")%>%
    summarise(`bad hits` = n()) %>%
    select(`bad hits`)
  )%>%
  mutate(`good hits` = `hits` - `bad hits`,
         player = "Judge")
Ohtani3 <- cbind(
  Ohtani1 %>%
    group_by(week)%>%
    summarise(pitches = n()) %>%
    select(week, pitches),
  Ohtani2 %>%
    group_by(week) %>%
    summarise(hits = n()) %>%
    select(hits),
  Ohtani2 %>%
    group_by(week) %>%
    filter(outcome=="HitBad")%>%
    summarise(`bad hits` = n()) %>%
    select(`bad hits`)
  )%>%
  mutate(`good hits` = `hits` - `bad hits`,
         player = "Ohtani")
Betts3 <- cbind(
  Betts1 %>%
    group_by(week)%>%
    summarise(pitches = n()) %>%
    select(week, pitches),
  Betts2 %>%
    group_by(week) %>%
    summarise(hits = n()) %>%
    select(hits),
  Betts2 %>%
    group_by(week) %>%
    filter(outcome=="HitBad")%>%
    summarise(`bad hits` = n()) %>%
    select(`bad hits`)
  )%>%
  mutate(`good hits` = `hits` - `bad hits`,
         player = "Betts")

Judge3 <- Judge3 %>%
  mutate(`hits last week` = append(Judge3$hits[1:26], 0, 0))
Ohtani3 <- Ohtani3 %>%
  mutate(`hits last week` = append(Ohtani3$hits[1:26], 0, 0))
Betts3 <- Betts3 %>%
  mutate(`hits last week` = append(Betts3$hits[1:18], 0, 0),
         `hits last week`) %>%
  mutate(`hits last week` = ifelse(week == 21, 0, `hits last week`))

Dataset <- rbind(
  Judge3,
  Ohtani3,
  Betts3
)
```

```{r}
#Model 1
Pois1 <- glm(`good hits` ~ offset(log(pitches)) + `hits last week`, family = poisson, data=Dataset)
Dataset <- Dataset %>%
  mutate(fittedP1 = fitted(Pois1))
```

$$
y_t \sim Poisson(\lambda_t)
$$

$$
log(\lambda_t)=log(\text{pitches}_t)+\beta_0+\beta_1x_{t-1}
$$

```{r}
GeneralPois1 <- glmer(
  `good hits` ~ offset(log(pitches))+`hits last week` + (1|week), family="poisson", data=Dataset
)
Dataset <- Dataset %>%
  mutate(fittedP2 = fitted(GeneralPois1))
```

$$
y_t \sim Pois(\lambda_t)
$$

$$
log(\lambda_t) = log(\text{pitches}_t)+\beta_0+\beta_1x_{t-1}+\epsilon_t
$$

$$
\epsilon_t \sim N(0, \sigma^2)
$$

```{r}
#Model 3
GeneralPois2 <- glmer(
  `good hits` ~ offset(log(pitches))+`hits last week` + (1+week|player), family="poisson", data=Dataset)
Dataset <- Dataset %>%
  mutate(fittedP3 = fitted(GeneralPois2))
```

$$
y_{t,i} \sim Pois(\lambda_{t,i})
$$

$$
log(\lambda_{t,i}) = log(\text{pitches}_t)+\beta_0+\beta_1x_{t-1}+\epsilon_t+V_{t,i}
$$

$$
\epsilon_t \sim N(0, \sigma^2)
$$

$$
V_{t,i} \text{ is the differencing term between the players}
$$


```{r}
paste(
  "p-value between the null model and our model 1:", 
  round(anova(Pois1, test="Chi")$`Pr(>Chi)`[2],3)
  )
paste(
  "p-value between our model 1 and model 2:", 
  round(anova(Pois1, GeneralPois1, test="Chi")$`Pr(>Chi)`[2],3)
  )
paste(
  "p-value between our model 2 and model 3:", 
  round(anova(GeneralPois1, GeneralPois2, test="Chi")$`Pr(>Chisq)`[2],3)
  )
paste(
  "p-value between our model 3 and the saturated model:", 
  round(1-pchisq(deviance(GeneralPois2), df.residual(GeneralPois2)),3)
  )
```

```{r}
Dataset %>%
  ggplot(aes(x=week, color=player))+
  geom_point(aes(y=`good hits`, shape=player), size=2)+
  geom_line(aes(y=`good hits`))+
  theme_minimal()+
  labs(title="Observed good hits by player",
       x="Week Played",
       y="Good hits observed")
```

```{r}
Dataset %>%
  group_by(player) %>%
  summarise(
    `weeks played` = n(),
    `tot. pitches` = sum(`pitches`),
    `tot. good hits` = sum(`good hits`),
    `avg. good hits per week` = mean(`good hits`),
    `sd. good hits per week` = var(`good hits`)
  )

Dataset %>%
  ggplot(aes(fill=player))+
  geom_histogram(aes(x=`good hits`))+
  scale_color_manual(values=c("Betts"="red", "Judge"="green", "Ohtani"="blue"))+
  scale_x_continuous(limits=c(-1,6))+
  theme_minimal()
```
